# Generated by Django 3.1 on 2020-08-23 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydb_data_layer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='accomodation_type',
            new_name='accommodation_type',
        ),
    ]
