# Generated by Django 3.1 on 2020-09-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydb_data_layer', '0007_auto_20200903_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='user_id',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='search',
            name='user_id',
            field=models.FloatField(null=True),
        ),
    ]
