# Generated by Django 3.1 on 2020-09-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydb_data_layer', '0008_auto_20200907_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
